#! /bin/bash

# Retrieve arguments
port=$1
nickname=$2
contact=$3
policy=$4

app=torrelay
torconf=/etc/tor/torrc

# Check port availability
sudo yunohost app checkport $port
if [[ ! $? -eq 0 ]]; then
	exit 1
fi

# Save app settings
sudo yunohost app setting $app port -v "$port"
sudo yunohost app setting $app nickname -v "$nickname"
sudo yunohost app setting $app contact -v "$contact"
sudo yunohost app setting $app policy -v "$policy"
# install via apt-get
sudo apt-get update > /dev/null 2>&1
sudo apt-get install -y tor > /dev/null 2>&1

#copying conf file
sudo cp ../conf/torrc $torconf
sudo chmod 660  $torconf
sudo chown :debian-tor $torconf

#configuring with given settings
sudo sed -i "s/YNH_LISTENING_PORT_PLACEHOLDER/$port/g" $torconf
sudo sed -i "s/YNH_NICKNAME_PLACEHOLDER/$nickname/g" $torconf
sudo sed -i "s/YNH_CONTACT_INFO_PLACEHOLDER/$contact/g" $torconf
if [[ "$policy" = "Yes" ]]; then
	sudo sed -i "s/YNH_EXIT_POLICY_PLACEHOLDER/accept/g" $torconf
else 
	sudo sed -i "s/YNH_EXIT_POLICY_PLACEHOLDER/reject/g" $torconf
fi

#open port in firewall
sudo yunohost firewall allow Both $port > /dev/null 2>&1
sudo yunohost firewall allow --ipv6 Both $port > /dev/null 2>&1

#starting tor service
sudo /etc/init.d/tor restart

#adding tor as a service
sudo yunohost service add tor -l /var/log/tor/log